FROM almalinux:8
RUN yum install nginx -y
CMD ["nginx", "-g", "daemon off;"]
ENV TRAINING="DEVOPS" \
      TRAINER="sivakumar" \
      DURATION="20hrs" \
      org.opencontainers.image.authors="jujjurisowjanya@gmail.com"